### ISSUE TITLE
Описать REST API методы в контроллере заказов

### ISSUE THREAD

**Issue by FirstIlyasIT** [TheSchoolboys/MastersAggregator#1]
1. В классе OrderController  создать методы, для : записи заказа( POST),  получении всех заказов для текущего пользователя(GET), получение заказа по его id(GET)  и удаление заказа (DELETE) ; все действия через 
 2. В вики описать эти методы, их маршруты, входящие и исходящие параметры в формате json, а так же коды ответов.
 3. Создать по тесту для каждого метода с нормализованными данными.

**Comment by Ramzes-Epp** [comment]
может стоит создать папку file и в ней хранить данные - например user.json, image.json, .... и с файлов работать с данными?

**Comment by FirstIlyasIT** [comment]
> 

Я не понимаю, зачем тебе вообще нужны данные? Если для тестов и дебага, то добавь их в проект с тестами, можно даже в папку  static_file. В самом контроллере естественно никаких данных храниться не должно, репозиторий можно замокать, изспользуя NSubstitute или Moq.

**Comment by Ramzes-Epp** [comment]
ок,  то есть реализация тестовых данных в UserRepository, OrderRepository,ImageRepository (те что в последнем коммите)  - этого достаточно?

**Comment by Ramzes-Epp** [comment]
Еще вопрос -  по public UserController(BaseRepository…
…<User> repository) : base(repository) - не получается запустить через BaseRepository, можно реализовать общие методы (GetAll, GetById, Add) в BaseRepository но до меня не доходит как в BaseRepository подтянуть нужный мне репозиторий (например UserRepository и ImageRepository)

**Comment by FirstIlyasIT** [comment]
> 

Так поставь UserRepository вместо BaseRepository, наследование позволяет это сделать. А реализация тестовых данных в наших репозиториях не должно быть. Зачем они там ? Следующий этап будет, написание запросов в репозитории.

**Comment by Ramzes-Epp** [comment]
Добавил метод save  в контроллере, при добавление в свагер  нового экземпляра Order не может создать т.к ему не нравиться что использован абстрактный класс - текст ошибки свагера:
Не удалось создать экземпляр типа MastersAggregatorService.Models.Order. Сложные типы, привязанные к модели, не должны быть абстрактными или типами значений и должны иметь конструктор без параметров. Типы записей должны иметь один первичный конструктор. В качестве альтернативы присвойте параметру saveOrder ненулевое значение по умолчанию.

Глянь пожалуйста commit  не могу понять как исправить что бы метод Save мог и создавать и редактировать  Order https://github.com/TheSchoolboys/MastersAggregator/tree/MastersAggregatorBranchRomanLocal/MastersAggregatorService
